Add deep link support
moallemi/MultiNavHost pull request #6
Opened 2020-07-17 14:28 UTC by mehdiyari

Add deep link support for 
home(http://moallemi.me/home)
dashboard(http://moallemi.me/dashboard)
notifications(http://moallemi.me/notifications)
pages(http://moallemi.me/pages/5)

2020-07-21 06:43 UTC, moallemi requested changes
@mehdiyari Thank you for your great job!

Your changes handle deep links nicely, but there is a small issue:

Go through these steps:
1- open app (now you are on home tab)
2- open notifications tab via deep link:
```
adb shell am start -a android.intent.action.VIEW -d "http://moallemi.me/notifications"
```
3- app navigates to notifications tab. now press back to go back to previous tab
**Actual result:** you have to press back button twice to go back to previous tab (home tab)
**Expected result:** you can navigate back to previous tab only by pressing back button once.

2020-07-21 06:43 UTC, moallemi commented on app/src/main/java/me/moallemi/multinavhost/MainActivity.kt
> +        if (savedInstanceState == null) tabManager.currentController = tabManager.navHomeController
please do not use single line `if` 

```suggestion
        if (savedInstanceState == null) {
            tabManager.currentController = tabManager.navHomeController
        }
```

2020-07-21 06:43 UTC, moallemi commented on app/src/main/java/me/moallemi/multinavhost/MainActivity.kt
> +        if (savedInstanceState == null && intent.action === Intent.ACTION_VIEW && intent?.data != null)
same comment here

2020-07-21 06:43 UTC, moallemi commented on app/src/main/java/me/moallemi/multinavhost/MainActivity.kt
> +            handleDeepLink()
same comment here

2020-07-22 05:55 UTC, moallemi approved these changes

2020-07-22 05:56 UTC, moallemi commented
Resolves #1

2020-07-22 05:56 UTC, merged

2020-07-22 06:38 UTC, mehdiyari commented
thanks @moallemi